/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#294CD6",
        "primary-dim": "#163ECA",
        "primary-container": "#859AFF",
        "primary-fixed": "#859AFF",
        "primary-fixed-dim": "#728BFF",
        "on-primary": "#F2F1FF",
        "on-primary-container": "#001868",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#001F7F",
        "secondary": "#9720AB",
        "secondary-dim": "#89089E",
        "secondary-container": "#FCBCFF",
        "secondary-fixed": "#FCBCFF",
        "secondary-fixed-dim": "#F9A7FF",
        "on-secondary": "#FFEEFB",
        "on-secondary-container": "#7C0091",
        "on-secondary-fixed": "#5D006D",
        "on-secondary-fixed-variant": "#8A0B9F",
        "tertiary": "#B60051",
        "tertiary-dim": "#A00047",
        "tertiary-container": "#FF8FA9",
        "tertiary-fixed": "#FF8FA9",
        "tertiary-fixed-dim": "#FF769B",
        "on-tertiary": "#FFEFF0",
        "on-tertiary-container": "#66002B",
        "on-tertiary-fixed": "#380014",
        "on-tertiary-fixed-variant": "#770033",
        "background": "#F4F6FF",
        "on-background": "#2A2F37",
        "surface": "#F4F6FF",
        "surface-dim": "#CDD5E4",
        "surface-bright": "#F4F6FF",
        "surface-tint": "#294CD6",
        "surface-variant": "#D6DDEC",
        "on-surface": "#2A2F37",
        "on-surface-variant": "#575C65",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#ECF1FD",
        "surface-container": "#E3E8F5",
        "surface-container-high": "#DCE3F0",
        "surface-container-highest": "#D6DDEC",
        "outline": "#727780",
        "outline-variant": "#A9ADB7",
        "error": "#B41340",
        "error-dim": "#A70138",
        "error-container": "#F74B6D",
        "on-error": "#FFEFEF",
        "on-error-container": "#510017",
        "inverse-surface": "#090E16",
        "inverse-on-surface": "#989DA7",
        "inverse-primary": "#6E88FF",
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        '5xl': '2.5rem',
        'full': '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['Manrope', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        'glass': '0 8px 32px 0 rgba(31, 38, 135, 0.07)',
        'glass-lg': '0 20px 50px rgba(42, 47, 55, 0.08)',
        'glass-xl': '0 40px 80px -15px rgba(42, 47, 55, 0.12)',
        'primary-glow': '0 20px 40px -10px rgba(41, 76, 214, 0.25)',
        'card-hover': '0 30px 60px -15px rgba(42, 47, 55, 0.15)',
        'nav': '0 4px 24px 0 rgba(42, 47, 55, 0.05)',
      },
      animation: {
        'float': 'float 20s ease-in-out infinite alternate',
        'float-slow': 'float 30s ease-in-out infinite alternate',
        'float-reverse': 'float 25s ease-in-out infinite alternate-reverse',
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
      },
      keyframes: {
        float: {
          '0%': { transform: 'translate(0, 0) scale(1)' },
          '100%': { transform: 'translate(30px, 20px) scale(1.1)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
