/** Route path constants */
export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_OTP: '/verify-otp',
  FLIGHTS: '/flights',
  FLIGHT_DETAIL: '/flights/:id',
  HOTELS: '/hotels',
  HOTEL_DETAIL: '/hotels/:id',
  FLIGHT_HOTEL: '/flight-hotel',
  PACKAGE_DETAIL: '/packages/:id',
  TOURS: '/tours',
  TOUR_DETAIL: '/tours/:id',
  MAP: '/map',
  DEALS: '/deals',
  DEALS_DETAIL: '/deals/:code',
  CITY_DETAIL: '/cities/:code',
  EXPLORE: '/explore',
  LANDMARK_DETAIL: '/landmarks/:id',
  CHECKOUT: '/checkout',
  BOOKING_CONFIRMATION: '/booking/confirmation',
  TRIP_PLANNER: '/trip-planner',
  SUPPORT: '/support',
  PROFILE: '/profile',
  BOOKINGS: '/bookings',
  TRIPS: '/trips',
  WISHLIST: '/wishlist',
  ABOUT: '/about',
  CAREERS: '/careers',
  CONTACT: '/contact',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  NOT_FOUND: '*',
};
